import { Injectable } from '@angular/core';
import {HttpClient, HttpHeaders, HttpParams,HttpContext} from '@angular/common/http';
import { Observable } from 'rxjs';
import { shareReplay } from 'rxjs/operators';
@Injectable({
  providedIn: 'root'
})
/*
Sample response:
{
  "name": "songs.json",
  "path": "VialRack/songs.json",
  "sha": "e281f19253bfa6b98d868272331790e3459602a6",
  "size": 348,
  "url": "https://api.github.com/repos/hardik-rajpal/gitdb/contents/VialRack/songs.json?ref=main",
  "html_url": "https://github.com/hardik-rajpal/gitdb/blob/main/VialRack/songs.json",
  "git_url": "https://api.github.com/repos/hardik-rajpal/gitdb/git/blobs/e281f19253bfa6b98d868272331790e3459602a6",
  "download_url": "https://raw.githubusercontent.com/hardik-rajpal/gitdb/main/VialRack/songs.json",
  "type": "file",
  "content": "<base 64 content here>",
  "encoding": "base64",
  "_links": {
    "self": "https://api.github.com/repos/hardik-rajpal/gitdb/contents/VialRack/songs.json?ref=main",
    "git": "https://api.github.com/repos/hardik-rajpal/gitdb/git/blobs/e281f19253bfa6b98d868272331790e3459602a6",
    "html": "https://github.com/hardik-rajpal/gitdb/blob/main/VialRack/songs.json"
  }
}
*/
export class GitdbService {

  apiBase:string= 'https://api.github.com/repos/hardik-rajpal/gitdb/contents/'
  dbs = {
    vialrackSongs:'/VialRack/songs.json'
  }

  private songs$?: Observable<any>;
  private literature$?: Observable<any>;
  private albums$?: Observable<any>;

  constructor(private http:HttpClient) { }
  getVialRackSongs(){
    if (!this.songs$) {
      const fileApiUrl = this.apiBase + this.dbs.vialrackSongs;
      this.songs$ = this.http.get(fileApiUrl).pipe(shareReplay(1));
    }
    return this.songs$;
  }
  // Generated by personal-scripts/scripts/ytmusic_export_playlists.py
  getPlaylists(){
    return this.http.get('assets/playlists.json');
  }
  // Hand-curated reading list at src/assets/literature.json
  getLiterature(){
    if (!this.literature$) {
      this.literature$ = this.http.get('assets/literature.json').pipe(shareReplay(1));
    }
    return this.literature$;
  }
  // Hand-curated album list at src/assets/albums.json
  getAlbums(){
    if (!this.albums$) {
      this.albums$ = this.http.get('assets/albums.json').pipe(shareReplay(1));
    }
    return this.albums$;
  }
}
