import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { shareReplay } from 'rxjs/operators';
import { MediumFeed } from 'src/data/medium';

@Injectable({ providedIn: 'root' })
export class MediumService {
  private cache$?: Observable<MediumFeed>;

  constructor(private http: HttpClient) {}

  // Generated by personal-scripts/scripts/medium_export.py
  getFeed(): Observable<MediumFeed> {
    if (!this.cache$) {
      this.cache$ = this.http
        .get<MediumFeed>('assets/medium.json')
        .pipe(shareReplay(1));
    }
    return this.cache$;
  }
}
